## Timeseries 1

**Description:** 


**Found in:**

**Contributor(s):**

**Data steward:**

**Point of contact:**

### Data sources

### Data aggregation

### Quality assurance

### Data analysis

### Header from file
Station Description:,San Sebastian Air Temperature - Spain,,
Region:,Bay of Biscay and the Iberian waters,,
Latitude:,43.31 N,,
Longitude:,2.04 W,,
Measurement Depth/Range:,,,
Long Term Averaging Period:,1991-2020,,
Long Term Mean:,13.77,,
Standard Deviation:,0.52,,
Spatial Coverage:,Data are collected from a fixed meteorological station,,
Vertical  Coverage:,Data represent air temperature at 251 m above mean sea level,,
Temporal Coverage:,Monthly data,,
Averaging Method:,Annual data are the arithmetic mean of the monthly data,,
Notes:,,,
Data Source:,Igeldo Meteorological Observatory (AEMet) in San Sebastian - Spain,,
Contact Name (email):,Almudena Fontán (afontan@azti.es),,
Location of source datasets:,Igeldo Meteorological Observatory (AEMet) in San Sebastian - Spain,,
Data Protection:,Include on ICES website for free distribution.,,
