## Extended Ellett Line - Hatton Rockall Basin - upper 800 m

**Description:** 


**Found in:**

**Contributor(s):**

**Data steward:**

**Point of contact:**

### Data sources

### Data aggregation

### Quality assurance

### Data analysis

### Header from file
Station Description:,Extended Ellett Line - Hatton Rockall Basin,
Region:,Hatton-Rockall Basin,
Latitude:,58.66 N,
Longitude:,16.50 W,
Measurement Depth/Range:,Upper 800 m,
Area:,"LINESTRING(-17.18 58.95,-13.6 57.6)",
Spatial coverage:,Data are collected from a fixed set of stations between Rockall and Hatton Bank,
Vertical coverage:,Data within potential density range sigma_zero = 27.20 to 27.50 kg/m**3 equating to approximately 30 m to 800 m depth,
Temporal coverage:,1 occupation per year (spring/summer),
Seasonal cycle:,"No adjustment for seasonal cycle, because cycle is not sufficiently well defined by the data set",
Reference:,"Holliday N.P. et al, 2015. Multidecadal variability of potential temperature, salinity and transports in the eastern subpolar North Atlantic. Journal of Geophysical Research: Oceans, 120(9), 5945-5967, 10.1002/2015JC010762.",
Notes:,http://projects.noc.ac.uk/ExtendedEllettLine/home,
Data Source:,National Oceanography Centre and Scottish Association for Marine Science - UK,
Contact Name (email):,Sam Jones (sam.jones@sams.ac.uk),
Location of source datasets:,British Oceanographic Data Centre,
Data Protection:,Include on ICES website for free distribution.,
Long Term Averaging Period:,1996-2020,1996-2020,,,,
Long Term Mean:,8.9379,35.2812,,,,
Standard Deviation:,0.357,0.0563,,,,
Averaging Method:,Mean of all data each year,
Notes:,Section average of stations from Hatton Bank at 59.12N, 17.67W to Rockall. Holliday et al. JGR. 2015; Data within potential density range 27.20-27.50 kg/m**3 - equating to approximately the upper 800m; http://projects.noc.ac.uk/ExtendedEllettLine/home,
Data Source:,National Oceanography Centre and Scottish Association for Marine Science - UK,
Contact Name (email):,Sam Jones (sam.jones@sams.ac.uk),
Location of source datasets:,British Oceanographic Data Centre,
Data Protection:,Include on ICES website for free distribution.,
