## Extended Ellett Line - Iceland Basin - Deep Ocean

**Description:** 


**Found in:**

**Contributor(s):**

**Data steward:**

**Point of contact:**

### Data sources

### Data aggregation

### Quality assurance

### Data analysis

### Header from file
Station Description:,Extended Ellett Line - Iceland Basin,
Region:,Iceland Basin,
Latitude:,60.00 N,
Longitude:,20.00 W,
Measurement Depth/Range:,Deep Ocean 2000-2700m,
Area:,"LINESTRING(-20.2 63.3,-20.0 60.0,-17.2 58.95)",
Spatial coverage:,Data are collected from a fixed set of stations between Iceland and Hatton Bank,
Vertical coverage:,Data with potential density  sigma_zero > 27.85 kg/m**3 equating to approximately 2000-2700 m depth,
Temporal coverage:,1 occupation per year (spring/summer),
Seasonal cycle:,"No adjustment for seasonal cycle, because cycle is not sufficiently well defined by the data set",
Reference:,"Holliday N.P. et al, 2015. Multidecadal variability of potential temperature, salinity and transports in the eastern subpolar North Atlantic. Journal of Geophysical Research: Oceans, 120(9), 5945-5967, 10.1002/2015JC010762.",
Notes:,http://projects.noc.ac.uk/ExtendedEllettLine/home,
Data Source:,National Oceanography Centre and Scottish Association for Marine Science - UK,
Contact Name (email):,Sam Jones (sam.jones@sams.ac.uk),
Location of source datasets:,British Oceanographic Data Centre,
Data Protection:,Include on ICES website for free distribution.,
Long Term Averaging Period:,1996-2020,1996-2020,,,,
Long Term Mean:,2.86,34.978,,,,
Standard Deviation:,0.11,0.011,,,,
Annual calculations:,Mean of all data each year,
