## North Icelandic Irminger Current

**Description:** 


**Found in:**

**Contributor(s):**

**Data steward:**

**Point of contact:**

### Data sources

### Data aggregation

### Quality assurance

### Data analysis

### Header from file
Station Description:,Siglunes Station 2-4 - North Iceland - North Icelandic Irminger Current - Spring,,,,,
Region:,3,,,,,
Latitude :,67 N,,,,,
Longitude:,18 W,,,,,
Measurement Depth/Range:,50-150 m,,,,,
Long Term Averaging Period:,1991-2020,1991-2020,,,,
Long Term Mean :,3.99,34.909,,,,
Standard Deviation:,1.00,0.099,,,,
Averaging method:,Average over 50-150 m in spring,,,,,
Notes:,,,,,,
Data Source:,Hafrannsoknastofnun - Iceland - Marine Research Institute ,,,,,
Contact Name (email):,Solveig R. Olafsdottir (solveig.rosa.olafsdottir@hafogvatn.is),Magnus Danielsen (magnus.danielsen@hafogvatn.is),,,,
Location of source datasets:,Hafrannsoknastofnun - Iceland - Marine Research Institute ,,,,,
Data Protection:,Include on ICES website for free distribution. ,,,,,
